name: Git Actions
run-name: Workflows

on: 
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Install Node
              uses: actions/setup-node@v3
              with:
                node-version: 18.x

            - name: Inicialize Node and install
              run: |
               npm init
               npm install
            
            - name: Install Express
              run: npm install express

